work_dir: "workdir/agibot_digital"

data:
  scene_type: "video"  # 'sceneflow' or 'video'
  height: 480
  width: 640
  rgb_path: "data/agibot_digital/observations/digitaltwin_3/ec210ba6-8c0f-4604-8953-e88e60d4acd2/video/head.mp4"
  fps: 15

generation:
  prompt_upsampler_ckpt: "/data2/yang_liu/Cosmos/checkpoints/Pixtral-12B"
  negative_prompt: "lowres, bad anatomy, bad hands, cropped, digital rendering, 3D rendering, computer rendering, virtual, worst quality"
  prompt:
    # agibot_digitaltwin_3_upsampled: "The robotic arm, equipped with a gripper, is positioned over a table. It carefully picks up an apple from the table's surface. The arm's precise movements and mechanical design are highlighted as it manipulates the fruit. The setting appears to be a controlled environment, possibly a lab or workshop, emphasizing the robot's functionality and accuracy."
    agibot_digitaltwin_3_studio: "at home, dining room, robotic arm, handbag, studio lighting" 

  # VidToMe args. See details in "src/vidtome/patch.py, apply_patch()"
  local_merge_ratio: 0.01
  global_merge_ratio: 0.01
  frame_range: [0, -1, 2]

seed: 123
base_config: plugin/VidToMe/configs/iclight_default.yaml