work_dir: "workdir/agirobot_digital"

data:
  scene_type: "video"  # 'sceneflow' or 'video'
  height: 480
  width: 640
  rgb_path: "data/agirobot_digital/observations/digitaltwin_0/0d960aec-079c-4827-9836-72fa5c8e6c9a/video/head.mp4"
  fps: 15

generation:
  prompt_upsampler_ckpt: "/data2/yang_liu/Cosmos/checkpoints/Pixtral-12B"
  negative_prompt: "machine, lowres, bad anatomy, bad hands, cropped, digital rendering, 3D rendering, computer rendering, virtual, worst quality"
  prompt:
    # agirobot_digitaltwin_0_upsampled: null
    agirobot_digitaltwin_0: "at home, living room, robotic arm, white table. The scene is well-lit by sunshine, highlighting the clean and organized workspace." 

  # VidToMe args. See details in "src/vidtome/patch.py, apply_patch()"
  local_merge_ratio: 0.9
  global_merge_ratio: 0.8
  frame_range: [0, 60, 2]

seed: 123
base_config: plugin/VidToMe/configs/iclight_default.yaml