work_dir: "workdir/agirobot_digital"

data:
  scene_type: "video"  # 'sceneflow' or 'video'
  height: 480
  width: 640
  rgb_path: "data/agirobot_digital/observations/digitaltwin_5/1e01900f-798b-467f-bf60-e227c3ae3073/video/head.mp4"
  fps: 15

generation:
  prompt_upsampler_ckpt: "/data2/yang_liu/Cosmos/checkpoints/Pixtral-12B"
  negative_prompt: "lowres, bad anatomy, bad hands, cropped, digital rendering, 3D rendering, computer rendering, virtual, worst quality"
  prompt:
    # agirobot_digitaltwin_5_upsampled: "The video depicts a robotic arm performing a task on a wooden table. The robot, equipped with a gripper, interacts with various objects including a green bowl, a yellow box, a small card, and a green block. The scene is set near a window, allowing natural light to illuminate the workspace. The robotic arm carefully picks up and manipulates the objects, demonstrating precision and control in a simulated environment."
    agirobot_digitaltwin_5_natural: "The video depicts a robotic arm performing a task on a wooden table. The scene is set near a window, allowing natural light to illuminate the workspace. The robotic arm carefully picks up and manipulates the objects, demonstrating precision and control" 

  # VidToMe args. See details in "src/vidtome/patch.py, apply_patch()"
  local_merge_ratio: 0.01
  global_merge_ratio: 0.01
  frame_range: [0, -1, 2]

seed: 123
base_config: plugin/VidToMe/configs/iclight_default.yaml