data:
  rgb_path: "data/scand/A_Spot_Parlin_Parlin_Wed_Nov_10_51.avi"

generation:
  prompt:
    A_Spot_Parlin_Parlin_Wed_Nov_10_51: 

base_config: plugin/VidToMe/configs/scand/iclight_scand_vidtome.yaml