data:
  rgb_path: "data/scand/A_Spot_Dobie_Fountain_Fri_Nov_12_84.avi"

generation:
  prompt:
    A_Spot_Dobie_Fountain_Fri_Nov_12_84: 

base_config: plugin/VidToMe/configs/scand/iclight_scand_vidtome.yaml