data:
  rgb_path: "data/droid_raw/Sat_Nov_25_18:14:57_2023/recordings/MP4/32907025.mp4"

generation:
  prompt:
    Sat_Nov_25_18:14:57_2023: 

base_config: plugin/VidToMe/configs/droid/iclight_droid_vidtome.yaml