sd_version: "1.5" # In ['2.1', '2.0', '1.5', 'depth', 'iclight']
work_dir: "workdir/waymo/edge_vidtome_opt"

data:
  scene_type: "video"  # 'sceneflow' or 'video'
  height: 640
  width: 960
  fps: 15

inversion:
  save_path: "${work_dir}/latents"
  force: True

generation:
  control: "softedge"
  control_scale: 0.4
  
  prompt_upsampler_ckpt: "/data2/yang_liu/Cosmos/checkpoints/Pixtral-12B"
  negative_prompt: "lowres, bad anatomy, bad hands, cropped, digital rendering, 3D rendering, computer rendering, virtual, worst quality, reflective"

  # VidToMe args. See details in "src/vidtome/patch.py, apply_patch()"
  local_merge_ratio: 0.6
  global_merge_ratio: 0.5
  frame_range: [0, -1, 1]

  alpha_t: 0.0

  guidance_scale: 7.5 # CFG scale

  #LoRA configs:
  use_lora: True
  lora:
    pretrained_model_name_or_path_or_dict: "artificialguybr/pixelartredmond-1-5v-pixel-art-loras-for-sd-1-5"
    weight_name: "PixelArtRedmond15V-PixelArt-PIXARFK.safetensors"
    adapter_name: "pixel"
    adapter_weights: 1.0

post_opt:
  apply_opt: True

seed: 123
base_config: plugin/VidToMe/configs/iclight_default.yaml